### ISSUE TITLE
Help with financing fman

### ISSUE THREAD

**Issue by eandmsz** [fman-users/fman#792]
Hi,

 I was thinking about ways that can help the project to get it's funding, so I came across the GitHub sponsors feature: https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/

 My main problem with donations is that the sponsors doesn't really feel they get anything for their money, so it's just a money sink.
 I think it would be great to somehow tie the donation tiers to specific feature requests, and when a certain amount has been collected the developer can commit to develop the requested feature. This way the features that are important for many people can be funded and I know people who is willing to pay in this form.
 Unfortunately Github sponsor tiers are designed to be a monthly donation like on Patreon, and not really a funding model like Kickstarter, so it probably needs some trust from the sponsors, but I think it could work.

BRs
/Andras

**Comment by mherrmann** [comment]
It's a cool idea. Thank you for thinking about it Andreas. The idealist in me wants it to succeed. The cynic (after many interactions online) believes it won't work because most people just want things for free and don't like to pay for stuff. I'm open to suggestions how it could realistically be made to work, in a way that takes human nature into account and also isn't a huge extra time drag on me.

**Comment by eandmsz** [comment]
It's really hard I know. Lots of people expect free sw, some just doesn't have the money to spend and some just have a wrong mindset about it. But most people doesn't realize how many work hours go into software development, testing, administration, code refactoring, etc. and calculating with Western European wages it can easily reach thousands of euros for just a single feature that seems to be only a few hours work for an outsider.

**I think what you can do is:**
1. Add fman to the Apple AppStore for macOS. That's where the paying customers are and I would totally pay for getting it from a trusted store with an easy one click installation. You can put a higher price for it as Apple takes 30% and you will have some extra work with this anyway. You might need to stop selling licenses for the macOS version via your website if you do this, but I think it's worth it. Especially that Apple tries to really make it hard for users to get their applications outside of the AppStore. Also: They are just moving to ARM based processors, so you will need to work on compiling it to that as well, which is extra work and I think could be a good reason to move fman to the AppStore now.

2. Setup Github Sponsors tiers and tell people what money is enough for what. For example:
 100 EUR/month - Work more on simple fixes
 500 EUR/month - Doing optimizations and fixes for more troublesome things
 1000 EUR/month - Add X, Y features that are highly requested and can be done realativly easily
 2000 EUR/month - Develop some more complex features
 5000 EUR/month - Work on fman in full time
 10000 EUR/month - Hire people that can help out with the work
And set up the tiers and "rewards" like:
 (I wouldn't do a 1 EUR tier as it's just too low)
 5 EUR/month - "Buy me one coffee every month"
 10  EUR/month - "Buy me a beer every month that is twice as effective as coffee :D"
 xx EUR/month - "Your name will appear in the list of Sponsors under About" (or something like that)

Of course you should advertise this on the fman website opening page and maybe do a blog post every now and then about how much money was collected and asking people who hasn't joined yet to join. I think it's a good idea to compare this sponsorship to a Netflix or Youtube Premium subscription, where you actually don't get much for your 10 EUR/month, while with fman you can actually be part of creating something useful.

**Comment by eandmsz** [comment]
**I would like to highlight one more thing:**

I think the general need for a file manager has decreased a lot in the last 10 years due to technology changes. We don't download music or movies or games anymore because we have cheap music and movie streaming alternatives and people either play online so they buy the game or they find some free games to spend time with. We take pictures with smartphones instead of cameras and organize pictures on the phone and and either store them in a cloud or transfer them to a computer (when the phone is full), but my main point is that people are not really organizing their stuff on their computers anymore, because we don't have anything to organize and actually lots of people are not buying new  PCs and Laptops because they are using their smartphone or tablet for everything they need.

 However, there is still a need for file managers, but I think it is becoming a more professional use case.
Programming, tinkering with RaspberryPi, designing 3D printable stuff, editing video footages, sorting lots of photos made with a professional DSLR camera, creating 3D assets, etc, they are all either hobby and professional work use cases, basically doing anything productive... **therefore I think you should raise the price** of fman by a lot. Someone who is only occasionally need a file manager won't pay for it anyway in my opinion, however someone who needs it for work or it is the last piece that keeps him moving from Windows to Linux or macOS will pay for it,
 SublimeText costs 80 USD right now, and that's a lot of money if you are a student or just want a text editor that you occasionally use, but if you actually use it every day for your work/hobbies then 80 USD is really worth it.

 Obviously you don't want to upset your customers, so before raising the price it would be good to develop a few missing and commonly requested features that are easy to do and keeping a lot of people from switching. And maybe provide a cheap upgrade path for existing customers.

**Comment by ekillops** [comment]
I like these ideas. There are not many alternative options for good keyboard driven file managers on Windows so I plan to continue using fman for my daily developer work and I would love to see it continue to evolve with new features (assuming they fit in with Michael's vision and philosophy for the program). I would happily contribute to funding development of features for fman, or pay 80 USD.

**Comment by raguay** [comment]
Why not do a Kickstarter or GoFundme campaign for new features? Both are a
one time donation for a specific change with extended bonuses if you want.
Many new games are using those platforms for funding their development and
initial deployments.

I doubt you can get this program onto the app store since it's mostly
Python with extensions. The app store is getting harder and harder to get
apps like that on to it. If you want that type of route, I would suggest
SetApp. It's a subscription service to over 100 programs. As people use the
programs, the authors get a percentage of sales. I don't know all the
details, but it seems to be working well for many. SetApp has hundreds of
users that would instantly come to know what fman is. Very effective
advertising.

That's my two cents.

Richard

**Comment by raguay** [comment]
But, SetApp is Mac/iOS only right now. They are looking to expand into the
Windows arena, but I don't know when.

**Comment by mherrmann** [comment]
I always think it's best to have honest conversations to find solutions, so here's a blurt out of what's in my head.

fman's current revenue of a few hundred Euros per month justifies me staying involved with the project. But barely. A few weeks ago, a Windows update broke the Windows installer so I had to fix that. Similarly, macOS updates sometimes break fman. I respond to issues here and to people who email me. But at the rate I charge now for consulting work, fman's income covers maybe 2-3 hours per month of my time investment.

When I created fman, I had this big dream of creating a product I myself wanted and love. I spent more than 3,000 hours - or two years of my life - creating it. As you all know, the financial payoff of this has been very poor. I love fman and used it every day. But if I'm honest, in terms of my career, it has not been a good investment. I was young and naive but regret wasting years of my limited life.

I'm 33 now. I've been self-employed for 8 years. While I was working on fman for the love of it, I was making €30k per year. Not from fman, but mostly from previous businesses that generate passive revenue. Some time ago, I asked myself: I'm a very qualified developer and could be making €100k per year in Austria. Do I really want to waste my life working on passion projects? Yes I like my work. But there are many other things I'd like to do, without having to earn money from it.

Since switching strategies, my yearly income rose to €70k (before tax) last year and will exceed €100k this year. I've found new projects (and consulting work) that are less romantic, but pay very well. And the better they pay, the cooler and actually more technically interesting the projects are.

All this gives me little (or actually no) incentive to spend more time on fman than I am currently spending, when I know that my hourly rate from working on fman for thousands of hours is on the order of €10. My life is too short to continue doing that. The few hundreds of € that fman makes justify me making sure it continues to run for other people as well. But not more than that.

At the same time, I think fman is pretty good. I have no issues with it in my daily work. None. It's not too slow. I don't need custom themes and (for my basic use cases) have not run into any bug I can remember.

Regarding your suggestions:

I only hear horror stories about Apple's App Store. It's already a pain to have Apple notarize fman so users who start it for the first time don't get an error "This application is untrusted and can't be opened". I can only imagine how painful it will be to make it available on the App Store. Maybe it will lead to more sales. But I'm not so sure. fman's target audience are power users. They are perfectly capable of downloading and installing a `dmg` file. I am doubtful that investing time into bringing fman to the App Store (and keeping it there!) will pay off financially.

Similarly with Kickstarter, or other sponsorship options. These things don't run themselves. I'd have to set them up, do marketing for them (esp. in case of Kickstarter), create nice images etc. I am doubtful that enough people will pay enough to make it worthwhile.

I can see two routes. I could raise prices to €80 and in return offer lifetime licenses. This is easy for me to do. If it brings fman's revenue above €2,000, then I can again justify spending more time on development work. I don't think it will, but it's easy to try.

The second route tempts the idealist in me, but I don't think it will work. I could open source fman and make it available for free. For each requested improvement on the issue tracker, there could be a payment link where people can contribute any amount of money they want to have the improvement implemented. If the contributions for a feature make it worth my while, I could implement it. Or, alternatively, someone else might implement the feature and send a pull request. If I accept it, then that person would receive the money. In all cases, I could take a 20% cut for my ongoing administrative efforts.

The problem with the second route again is that it's risky. I now know that fman makes a few hundred € per month, so I can keep it alive. The second route might put that down to 0, while at the same time requiring lots of admin time from me. It also requires a non-negligible initial investment of my time to set everything up. And again, at a big risk of reducing my financial reward for working on fman even further.

**Comment by wensle** [comment]
What about donating fman to the community? I've read the comments above. And I think I understand what you're saying. It's not worth it anymore to invest time in this project. Time spent on fman's development will reduce your income signnificantly. So why not transfer the ownership of fman to the community or someone else? I would really want to see fman continue to exist alive and well. But I don't think that will happen unless you decide what the future of fman will be. My apologies in advance if I came across as harsh and overcritical.

**Comment by mherrmann** [comment]
For now, it's still worth my time to keep fman going for the few thousand Euros it makes per year. So I would not want to donate it. I would however be open to selling it. Typical going rates for such businesses are 3-4x yearly income. If anybody wants to take me up on this, my email is on my [personal home page](https://herrmann.io).

**Comment by 5472qaywsx** [comment]
Maybe you could reason the other way round: how much would a one time licence cost, and how much the yearly upgrade fee, to make it interesting for you to work on more regularly? (you don't have to answer here, it's your business!)
How many of the actual subscribers would be interested in paying that fee? (maybe that you could ask them directly)
How many subscribers do you need to make it economically viable as a project?

**Comment by rasivasu** [comment]
@mherrmann I think it will help to tie the product to the PPP of user's country, at least loosely.  70 Euros is a lot of money in many parts of the world, especially when companies are unwilling to buy this product for its engineers and individuals have to pay the money from their pockets.

**Comment by themilkman** [comment]
I must admit, I am a bit upset about the current situation.

I bought and renewed a license since I wanted to support this little project and tool. I use it from time to time and when I do so, I really like it. And as a developer I now how much time is invested in software - thus paying for it essential.

Generally I do not like subscription models but in this case I made a exception. The main reasons was the Open Source Promise you gave. I really liked the idea that I do not invest in a product that might 'die'. I thought this would be a great deal for both sides.

Quite a couple of months ago I noticed that the commit-section was removed from the main page of fman and I think a few hints regarding the OS Promise were removed too (not sure about the latter).

Now I see there is a lifetime license for 70€. No blog entry about changed license terms. No deal for subscribed users. And again no sentence about the OS Promise.

This annoys me quite a bit.

(I don't want to talk about the price generally although I think for a product like Sublime Text you get way more for that amount of money. But okay, pricing generally is completely your business decision.)

But now I read here that you'd be even willing to sell your product. And here we are at a point where I start to feel betrayed regarding the Open Source Promise. Yes, it was a promise, not a contract. But not keeping a promise is a no go for me in this case.

Without a soon official update on this I will definitely cancel my subscription. Not because I don't want to keep supporting fman but because of lost trust and irritation.

**Comment by mherrmann** [comment]
> Without a soon official update on this

I am generally very fast to respond to emails and points raised here, so no reason to press this.

It seems there is frustration on both sides - yours and mine. And I think both are understandable. Feel free to cancel your old subscription. Your license key will still be good for newer versions.

I think I explained the frustration from my side with the project in other posts above, so won't reiterate them here.

**Comment by mherrmann** [comment]
@rasivasu I'll keep it in mind, thanks.

**Comment by themilkman** [comment]
> > Without a soon official update on this
> 
> I am generally very fast to respond to emails and points raised here, so no reason to press this.

I guess you know what I mean - a official blog entry or something. By "soon"  I mean that I'd expect this for transparency. It is not that those term changes are small and that they would have been done just yesterday. It is something which has to be explained to customers.
I know that you respond to emails friendly and nearly immediately (which is fascinating :)), but this is not the topic.

> It seems there is frustration on both sides - yours and mine. And I think both are understandable. 

They are, I do understand it. 

My whole point is your OS Promise. 

Generally of course no one has the right to judge your business decisions because that's obviously all up to you.

**Comment by drasbeck** [comment]
@mherrmann It is evident, from your comments, that you are neither releasing the source code (as per https://fman.io/blog/transparency/) nor _updating_ fman anymore. You are planning on maintaining it at best. As @themilkman points out, you made a promise, and it hurts when promises are broken and trust is lost.

I sadly cannot justify this behavior with a yearly subscription. I know you are offering a perpetual license now, but I have been with you since the early alpha, happily paying since March 1st, 2017, and thus buying a perpetual license today, at the same price as a new user just hopping aboard now doesn't sit right with me either.

I am sad to go and I am also sad to hear that the project simply didn't pan out for you.

So long and thanks for all the fish.

**Comment by mherrmann** [comment]
I will close this issue now. I have no interest in being criticised for an hourly wage of € 8 or so after thousands of hours.
